routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/cleaner/register', function () {
    return view('auth/cleanerregister');
});
Route::get('/', function () {
    return view('welcome');
});
Route::any('sender', function () {
    $txt = request()->txt;
	echo $txt;
	if(isset($txt) && $txt != '')
	event(new \App\Events\FormSubmitted($txt));
	return view('sender');
});

Route::get('payment', 'PayPalController@payment')->name('payment');
Route::get('cancel', 'PayPalController@cancel')->name('payment.cancel');
Route::get('payment/success', 'PayPalController@success')->name('payment.success');
Route::get('/stripe', 'MyStripeController@index');
Route::post('/store', 'MyStripeController@store')->name('stripe.store');	
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/dbupdate', 'Controller@dbupdate')->name('dbupdate');
Route::any('/getLocation', 'Controller@getLocation')->name('getLocation');

Route::group(['middleware' => 'auth','before'=>'auth','after'=>'no-cache'], function() {
	Route::post('/bookcleaner/{id}', 'HomeController@bookcleaner')->name('bookcleaner');
	Route::any('/searchcleaner', 'HomeController@searchcleaner')->name('searchcleaner');

	
    Route::get('/plans', 'PlanController@index')->name('plans.index');
    Route::get('/plan/{plan}', 'PlanController@show')->name('plans.show');
	Route::post('/subscription', 'SubscriptionController@create')->name('subscription.create');
	Route::post('/addreview', 'HomeController@addreview')->name('addreview');
	Route::any('/cancelschedule/{id}', 'HomeController@cancelschedule')->name('cancelschedule');
	//Route::get('orderlist', 'HomeController@orderlist')->name('orderlist');
	Route::post('profile/update', 'HomeController@profile_update')->name('profile_update');
	
	Route::any('/taskdecline/{id}', 'HomeController@taskdecline')->name('taskdecline');
	Route::any('/taskaccepted/{id}', 'HomeController@taskaccepted')->name('taskaccepted');
	Route::any('/markascomplete/{id}', 'HomeController@markascomplete')->name('markascomplete');
	Route::any('/addCalendarTime', 'HomeController@addCalendarTime')->name('addCalendarTime');
	Route::any('/cleaner/{id}', 'HomeController@cleanerprofile')->name('cleanerprofile');
	Route::any('/cleaner/calendar/details/{dtd}', 'HomeController@cleanercalendardetails')->name('cleanercalendardetails');	
	
	Route::any('/cleaner/delete/calendar/{id}', 'HomeController@deletecalendar')->name('deletecalendar');	
	Route::post('sendmsg', 'HomeController@sendmsg');	
	Route::any('/msghistory/{id}', 'HomeController@msghistory')->name('msghistory');	
	
	Route::any('/customer/{id}', 'HomeController@customer')->name('customer');	
	Route::any('cleanerCalendarTime', 'HomeController@cleanerCalendarTime');	
	Route::any('cleanerCalendarAvailableTime', 'HomeController@cleanerCalendarAvailableTime');	
	Route::any('getWorkOrder/{id}', 'HomeController@getWorkOrder');	
	Route::any('selectCleanerWorkOrder/{cleanerId}/{workorder_id}', 'HomeController@selectCleanerWorkOrder');	
	


	Route::any('testmail', 'HomeController@testmail');
	
	
});
Route::group(['prefix' => 'admin', 'middleware' => ['web','auth'],'before'=>'auth','after'=>'no-cache'], function (){
	Route::resource('location','LocationController');
	Route::resource('user','UserController');
	Route::get('calendar', 'UserController@calendar')->name('calendar');
	Route::get('calendar-master', 'UserController@calendarmaster')->name('calendarmaster');
	Route::get('cleaner', 'UserController@cleaner')->name('cleaner');
	Route::post('/cleaner/slot/create', 'UserController@slot_create')->name('slot_create');
	Route::post('/cleaner/slot/resize', 'UserController@slot_resize')->name('slot_resize');
	Route::post('/cleaner/slot/move', 'UserController@slot_move')->name('slot_move');
	Route::get('orderlist', 'UserController@orderlist')->name('orderlist');
	Route::get('orderlist/cancel', 'UserController@cancel')->name('orderlist.cancel');
	Route::get('orderlist/payment/{id}', 'UserController@payment')->name('orderlist.payment');
});

Route::get('google', function () {
    return view('googleAuth');
});
    
Route::get('auth/google', 'Auth\LoginController@redirectToGoogle');
Route::get('google-login', 'Auth\LoginController@handleGoogleCallback');

Route::get('auth/google/login', 'Auth\LoginController@redirectToGoogleNew');
Route::get('google_login', 'Auth\LoginController@handleGoogleCallbackNew');


Route::get('auth/facebook', 'Auth\FacebookController@redirectToFacebook');
Route::get('auth/facebook/callback', 'Auth\FacebookController@handleFacebookCallback');

resources/views/UserCRUD/01-edit.blade.php
@extends('layouts.app')
 

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="float-left">
                <h2>Cleaner Details</h2>
            </div>
            <div class="float-right">
                <a class="btn btn-primary" href="{{ route('user.index') }}"> Back</a>
            </div>
        </div>
    </div>


    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    {!! Form::model($user, ['method' => 'PATCH','route' => ['user.update', $user->id]]) !!}
    <div class="row border border-primary bg-white p-2">


        <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
                <strong>Name:</strong>
                {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!}
            </div>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
                <strong>Email Id:</strong>
                {!! Form::text('email', null, array('placeholder' => 'Email Id','class' => 'form-control')) !!}
            </div>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
                <strong>Phone Number</strong>
                {!! Form::text('phone_number', null, array('placeholder' => 'Phone Number','class' => 'form-control')) !!}
            </div>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
                <strong>Location</strong>
                {!! Form::text('location_id', null, array('placeholder' => 'Location','class' => 'form-control')) !!}
            </div>
        </div>
				




        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary float-left">Submit</button>
        </div>

    </div>
    {!! Form::close() !!}

	
	<div class="row border border-primary bg-white p-2">
	
	</div>
	
		</div>
	</div>
</div>

@endsection

resources/views/UserCRUD/02-edit.blade.php
@extends('layouts.app')
 

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="float-left">
                <h2>Cleaner Details</h2>
            </div>
            <div class="float-right">
                <a class="btn btn-primary" href="{{ route('user.index') }}"> Back</a>
            </div>
        </div>
    </div>


    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    {!! Form::model($user, ['method' => 'PATCH','route' => ['user.update', $user->id]]) !!}
    <div class="row border border-primary bg-white p-2">


        <div class="col-xs-4 col-sm-4 col-md-4">
            <div class="form-group">
                <strong>Name : {{ $user['name'] }}</strong>
                {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!}
            </div>
        </div>
        <div class="col-xs-4 col-sm-4 col-md-4">
            <div class="form-group">
                <strong>Email Id:</strong>
                {!! Form::text('email', null, array('placeholder' => 'Email Id','class' => 'form-control')) !!}
            </div>
        </div>
        <div class="col-xs-4 col-sm-4 col-md-4">
            <div class="form-group">
                <strong>Phone Number</strong>
                {!! Form::text('phone_number', null, array('placeholder' => 'Phone Number','class' => 'form-control')) !!}
            </div>
        </div>
		<div class="col-xs-6 col-sm-6 col-md-6 d-nonew">
			<div class="form-group">
				<strong>Location</strong>
				<select class="form-control" name="location_id">
					@foreach(locationlist() as $val)
						<option value="{{ $val['id'] }}"  @if($val['id'] == $address[0]['location_id']){{ 'selected' }}@endif>{{ $val['name'] }}</option>
					@endforeach
				</select>
			</div>			
		</div>
        <div class="col-xs-6 col-sm-6 col-md-6 d-nonew">
            <div class="form-group">
                <strong>Address</strong>
                {!! Form::text('location_id', $address[0]['address_details'], array('placeholder' => 'Location','class' => 'form-control')) !!}
            </div>
        </div>
				




        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary float-left">Submit</button>
        </div>

    </div>
    {!! Form::close() !!}

	
	<div class="row border border-primary bg-white p-2">
	
    	<link type="text/css" rel="stylesheet" href="/calendar/calendamedia/layout.css" />

        <link type="text/css" rel="stylesheet" href="/calendar/themes/calendar_g.css" />
        <link type="text/css" rel="stylesheet" href="/calendar/themes/calendar_green.css" />
        <link type="text/css" rel="stylesheet" href="/calendar/themes/calendar_traditional.css" />
        <link type="text/css" rel="stylesheet" href="/calendar/themes/calendar_transparent.css" />
        <link type="text/css" rel="stylesheet" href="/calendar/themes/calendar_white.css" />

	
	<!-- daypilot libraries -->
        <script src="/calendar/js/daypilot/daypilot-all.min.js" type="text/javascript"></script>	
	
	
        <div class="main">

            <div style="float:left; width: 160px;">
                <div id="nav"></div>
            </div>
            <div style="margin-left: 160px;">

                <div class="space d-none">
                    Theme: <select id="theme">
                        <option value="calendar_default">Default</option>
                        <option value="calendar_white">White</option>
                        <option value="calendar_g">Google-Like</option>
                        <option value="calendar_green">Green</option>
                        <option value="calendar_traditional">Traditional</option>
                        <option value="calendar_transparent">Transparent</option>
                    </select>
                </div>

                <div id="dp"></div>
            </div>

            <script type="text/javascript">

                var nav = new DayPilot.Navigator("nav");
                nav.showMonths = 1;
                nav.skipMonths = 1;
                nav.selectMode = "week";
                nav.onTimeRangeSelected = function(args) {
                    dp.startDate = args.day;
                    dp.update();
                    loadEvents();
                };
                nav.init();

                var dp = new DayPilot.Calendar("dp");
                dp.viewType = "Week";
				dp.theme = "calendar_green";
                dp.eventDeleteHandling = "Update";

                dp.onEventDeleted = function(args) {
                    $.post("backend_delete.php",
                        {
                            id: args.e.id()
                        },
                        function() {
                            console.log("Deleted.");
                        });
                };

                dp.onEventMoved = function(args) {
                    $.post("backend_move.php",
                            {
                                id: args.e.id(),
                                newStart: args.newStart.toString(),
                                newEnd: args.newEnd.toString()
                            },
                            function() {
                                console.log("Moved.");
                            });
                };

                dp.onEventResized = function(args) {
                    $.post("backend_resize.php",
                            {
                                id: args.e.id(),
                                newStart: args.newStart.toString(),
                                newEnd: args.newEnd.toString()
                            },
                            function() {
                                console.log("Resized.");
                            });
                };

                // event creating
                dp.onTimeRangeSelected = function(args) {
					//alert(args.start);
                    //alert(args.start);
                    //var name = prompt("New event name:", "Available");
                    var name = "Available";
                    dp.clearSelection();
                    if (!name) return;
                    var e = new DayPilot.Event({
                        start: args.start,
                        end: args.end,
                        id: DayPilot.guid(),
                        resource: args.resource,
                        text: name
                    });
                    dp.events.add(e);

                    $.post("backend_create.php",
                            {
                                start: args.start.toString(),
                                end: args.end.toString(),
                                name: name
                            },
                            function() {
                                console.log("Created.");
                            });

                };

                dp.onEventClick = function(args) {
                    //alert("clicked: " + args.e.id());
                };

                dp.init();

                loadEvents();

                function loadEvents() {
                    dp.events.load("backend_events.php");
                }
    var e = new DayPilot.Event({
        start: new DayPilot.Date("2019-12-18T12:00:00"),
        end: new DayPilot.Date("2019-12-18T12:00:00").addHours(3),
        id: DayPilot.guid(),
        text: "Available"
    });
    dp.events.add(e);
            </script>

            <script type="text/javascript">
            $(document).ready(function() {
                $("#theme").change(function(e) {
                    dp.theme = this.value;
                    dp.update();
                });
            });
            </script>

        </div>
        <div class="clear">
        </div>


	
	
	
	</div>
	
		</div>
	</div>
</div>

@endsection

resources/views/UserCRUD/calendarmaster.blade.php
@extends('layouts.app')
 

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="float-left">
                <h2>Calendar Master</h2>
            </div>
            <div class="float-right d-none">
                <a class="btn btn-success" href="{{ route('user.create') }}"> Create New User</a>
            </div>
        </div>
    </div>


    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif


    <table class="table table-bordered table-striped table-dark">
        <tr>
            <th>Date</th>
            <th>Available Cleaner</th>
        </tr>
		@foreach ($calendarmaster as $key => $val)
		<tr>
			<td>{{ date('d/m/Y',strtotime($key)) }}</td>
			<td>
				<table>
				<tr>
				@foreach($val as $key01=>$data)
					<td>
						<a href="{{'/admin/user/'.$key01.'/edit'}}" style="color:#FFF;">{{ $users[$key01]['name']}}</a>
						<ul style="padding-left:inherit;">
						@foreach($data as $time)
							<li>{{$time['start_time'].'Hrs - '.$time['end_time'].'Hrs'}}</li>
						@endforeach
						@if(isset($bookingmaster[$key][$key01]))
						<li style="margin-top:10px; list-style:none;">Booking List</li>
						@foreach($bookingmaster[$key][$key01] as $time)
							<li>{{$time['from_time'].'Hrs - '.$time['to_time'].'Hrs'}}</li>
						@endforeach
						@endif
						</ul>
					</td>
				@endforeach
				</tr>
				</table>
			</td>
		</tr>
		@endforeach
    </table>


    <?php /*{!! $user->render() !!}*/?>

		</div>
	</div>
</div>
@endsection

resources/views/UserCRUD/cleaner.blade.php
@extends('layouts.app')
 

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="float-left">
                <h2>Cleaner List</h2>
            </div>
            <div class="float-right d-none">
                <a class="btn btn-success" href="{{ route('user.create') }}"> Create New User</a>
            </div>
        </div>
    </div>


    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif


    <table class="table table-bordered table-striped table-dark">
        <tr>
            <th>No</th>
            <th>Name</th>
            <th>Contact Number</th>
            <th>Address</th>
            <th width="280px">Action</th>
        </tr>
		@foreach ($users as $key => $user)
		<tr>
			<td>{{ ++$i }}</td>
			<td>{{ $user->name }}</td>
			<td>
				{{ $user->phone_number }}<br>
				<a href="mailto:{{ $user->email }}">{{ $user->email }}</a>
			</td>
			<td>
				@if(isset($address[$user->id]))
				@foreach($address[$user->id] as $val)
					City : {{ $location[$val['location_id']]}}<br>
					Address : {{ $val['address_details']}}
				@endforeach
				@endif
			</td>
			<td>
				<a class="btn btn-sm btn-primary" href="{{ route('user.edit',$user->id) }}">Edit</a><?php /**/ ?>
				{!! Form::open(['method' => 'DELETE','route' => ['user.destroy', $user->id],'style'=>'display:inline']) !!}
				{!! Form::submit('Delete', ['class' => 'btn btn-sm btn-danger']) !!}
				{!! Form::close() !!}
			</td>
		</tr>
		@endforeach
    </table>


    <?php /*{!! $user->render() !!}*/?>

		</div>
	</div>
</div>
@endsection

resources/views/UserCRUD/create.blade.php
@extends('layouts.app')


@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="float-left">
                <h2>Create New Item</h2>
            </div>
            <div class="float-right">
                <a class="btn btn-primary" href="{{ route('user.index') }}"> Back</a>
            </div>
        </div>
    </div>


    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    {!! Form::open(array('route' => 'user.store','method'=>'POST')) !!}
    <div class="row">


        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Title:</strong>
                {!! Form::text('name', null, array('placeholder' => 'Title','class' => 'form-control')) !!}
            </div>
        </div>


        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Description:</strong>
                {!! Form::textarea('description', null, array('placeholder' => 'Description','class' => 'form-control','style'=>'height:100px')) !!}
            </div>
        </div>


        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>


    </div>
    {!! Form::close() !!}
		</div>
	</div>
</div>

@endsection

resources/views/UserCRUD/index.blade.php
@extends('layouts.app')
 

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="float-left">
                <h2>Customer List</h2>
            </div>
            <div class="float-right d-none">
                <a class="btn btn-success" href="{{ route('user.create') }}"> Create New User</a>
            </div>
        </div>
    </div>


    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif


    <table class="table table-bordered table-striped table-dark">
        <tr>
            <th>No</th>
            <th>Name</th>
            <th>Contact Number</th>
            <th>Address</th>
            <th width="280px">Action</th>
        </tr>
		@foreach ($users as $key => $user)
		<tr>
			<td>{{ ++$i }}</td>
			<td>{{ $user->name }}</td>
			<td>
				{{ $user->phone_number }}<br>
				<a href="mailto:{{ $user->email }}">{{ $user->email }}</a>
			</td>
			<td>
				@if(isset($address[$user->id]))
				@foreach($address[$user->id] as $val)
					City : {{ $location[$val['location_id']]}}<br>
					Address : {{ $val['address_details']}}
				@endforeach
				@endif
			</td>
			<td>
				<a class="btn btn-sm btn-info"  onclick="getOrderdata({{$user->id}})"   >Order List</a>
				<?php /*<a class="btn btn-primary" href="#">Edit</a>{{ route('user.edit',$user->id) }}*/ ?>
				{!! Form::open(['method' => 'DELETE','route' => ['user.destroy', $user->id],'style'=>'display:inline']) !!}
				{!! Form::submit('Delete', ['class' => 'btn btn-sm btn-danger']) !!}
				{!! Form::close() !!}
				
			</td>
		</tr>
		<tr style="display:none;" id="orderlist_{{$user->id}}" class="ord_data">
			<td colspan="5" style="text-align:center;">
				@if(isset($subscription[$user->id]))
					<table id="tbl_{{$user->id}}" class="table table-bordered table-striped table-dark tbl" style="font-size:smaller;" >
						<thead>
							<tr>
								<th>SL.</th>
								<th>Date</th>
								<th>Invoice Id</th>
								<th>Plan Name</th>
								<th>Received Token</th>
								<th>Used Token</th>
								<th>Remaining Token</th>
							</tr>
						</thead>
						<tbody>
							@php($i = 0)
							@foreach($subscription[$user->id] as $row)
								<tr>
									<td>{{$i++}}</td>
									<td>{{$row['created_at']}}</td>
									<td>{{$row['stripe_id']}}</td>
									<td>{{$row['stripe_plan']}}</td>
									<td>{{$row['quantity']}}</td>									
									<td>{{$row['used_quantity']}}</td>									
									<td>{{($row['quantity']-$row['used_quantity'])}}</td>									
								</tr>
							@endforeach							
						</tbody>
					</table>
				@else
					No subscription plan brought by this user.
				@endif	
			</td>
		</tr>
		@endforeach
    </table>


    <?php /*{!! $user->render() !!}*/?>

		</div>
	</div>
</div>

<style>
.tbl th{
	color:#000;
	background-color:#929da7
}
.tbl th, .tbl td{
	padding:1px;
}
</style>
		
<div id="schedulebookingmodal" class="modaltaskdecline" style="display:none; max-width: 600px;width: 600px; padding:15px;">
	<div class="modal-body" style="color:#000;">
		<h3>Order List</h3>
		<table>
			<tr><th>SL.</th><th>Date</th><th>Plan Name</th><th>Purchased Date</th><th>Received Token</th><th>Used Token</th><th>Remaining Token</th></tr>
		</table>
	</div>
</div>
<a href="#schedulebookingmodal" id="schedulebooking" style="display:none;" rel="modal:open">Open Modal</a>
<script>
$(document).ready(function () {  
	//alert(99);
	$('#schedulebooking').click();
	//alert(44);
});
getOrderdata = function(){
	$('.tbl').hide();
	$('.ord_data').hide();
	$('#orderlist_'+arguments[0]).show();
	$('#tbl_'+arguments[0]).show();
}

</script>
@endsection

resources/views/UserCRUD/orderlist.blade.php
@extends('layouts.app')
 

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="float-left">
                <h2>Cleaning Order List</h2>
            </div>
            <div class="float-right d-none">
                <a class="btn btn-success" href="{{ route('user.create') }}"> Create New User</a>
            </div>
        </div>
    </div>


    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

	
    <table class="table table-bordered table-striped table-dark">
        <tr>
            <th>No</th>
            <th>Customer Details</th>
            <th>Cleaner Details</th>
            <th>Order Details</th>
            <?php /*<th>Ordered Date</th>
			<th>Paid Amt.</th>*/ ?>			
			<th>Scheduled Date</th>
			<th>Status</th>
			<th>Action</th>
        </tr>
		@php($i = 0)
		
		@foreach ($bookinglist as $key => $val)
			@if($val->cleaner_id == 0)
				@php($val->cleaner_id = 2)
			@endif
		<tr>
			<td>{{ ++$i }}</td>
			<td>
				{{ $userlist[$val->customer_id]->name }}<br>
				{{ $userlist[$val->customer_id]->email }}				
			</td>
			<td>
				<a href="{{ asset('/admin/user/'.$val->customer_id.'/edit')}}">{{ $userlist[$val->cleaner_id]->name }}</a><br>
				{{ $userlist[$val->cleaner_id]->email }}
			</td>
			<td>
				Job ID : {{$val->id}}<br>
				City : @if(isset($locationlist[$val->location_id])){{ $locationlist[$val->location_id]->name }}@endif<br>
				Address : <?php /*{{ $addresslist[$val->address_id]->address_details }}*/?>
			</td>
			<td>
				{{ date('d/m/Y',strtotime($val->dtd)) }}<br>
				{{ substr($val->from_time,0,5) }} - {{ substr($val->to_time,0,5) }}
			</td>
			<td>
				@if($val->status == 1)
					Pending
				@elseif($val->status == 2)
					Completed
				@elseif($val->status == 3)
					Cancel by User
				@elseif($val->status == 4)
					Accepted by Cleaner
				@elseif($val->status == 5)
					Canceled by Cleaner
				@elseif($val->status == 6)
					Cancel by Admin
				@elseif($val->status == 7)
					Reschedule by User	
				@elseif($val->status == 12)
					Paid ( {{date('d/m/Y h:i A',strtotime($val->updated_at))}} )
					Paid Amount : ${{$val->cleaner_amt}}
				@endif
				
				@if($val->rating)
					<br>Review : {{$val->rating}}
					@php($i = 0)
					@while($val->rating > $i)
						@php($i++)
						<?php /*<i class="fa fa-star" style="font-size: large;" ></i>
						<i class="icon-ln icon-ln-star"></i>*/ ?>
					@endwhile
				@endif
			</td>
			<td>
				@if($val->status == 1)
					<a class="btn btn-sm btn-primary" href="{{ route('orderlist.cancel',$val->id) }}">Cancel</a>
				@elseif($val->status == 2)
					<a class="btn btn-sm btn-primary" href="{{ route('orderlist.payment',$val->id)}}">Mark as Paid of ${{$val->cleaner_amt}}</a>
				@endif
			</td>
		</tr>
		@endforeach
    </table>
    <?php /*{!! $user->render() !!}*/?>
		</div>
	</div>
</div>
@endsection